---
title: "bacterial_abundance"
author: "Madison Wright"
date: "11/13/2020"
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(dplyr)
```

# import data

```{r}
excel_sheets("Input_Data/week3/144L_2018_BactAbund.xlsx")

metadata <- read_excel("Input_Data/week3/144L_2018_BactAbund.xlsx", sheet = "Metadata")
glimpse(metadata)
# unique(metadata$Experiment)
# unique(metadata$Bottle)
# unique(metadata$Treatment)

data <- read_excel("Input_Data/week3/144L_2018_BactAbund.xlsx", sheet = "Data")
glimpse(data)

joined <- left_join(metadata, data)
# names(joined)
# summary(joined)
glimpse(joined)
```

# Prep Data
```{r message=FALSE, warning=FALSE}
cells <- joined %>% 
  mutate(Datetime = ymd_hm(Datetime),
         cells = Cells_ml * 1000) %>%
  group_by(Treatment, Bottle) %>% 
  mutate(interv = interval(first(Datetime), Datetime),
         hours = as.numeric(interv)/3600,
         days = hours/24) %>% 
  ungroup() %>% 
  select(Experiment:DNA_SampleID, hours, days, cells) %>% 
  drop_na(cells)

glimpse(cells)
```

# plot growth curves 
```{r fig.height=4, fig.width=6}
custom.colors <- c("Control" = "#E69F00", "Ash Leachate" = "#56B4E9", "Glucose_Nitrate_Phosphate" = "#009E73", "Mud Leachate" = "#CC79A7")
levels <- c("Control", "Glucose_Nitrate_Phosphate", "Ash Leachate",  "Mud Leachate")

cells %>% 
  mutate(dna = ifelse(DNA_Sample == T, "*", NA)) %>% 
  ggplot(aes(x = days, y = cells, group = interaction(Experiment, Treatment, Bottle))) +
  geom_line(aes(color = factor(Treatment, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(Treatment, levels = levels)), size = 3, color = "black", shape = 21) +
  geom_text(aes(label = dna), size = 12,  color = "#F0E442") +
  labs(x = "Days", y = expression(paste("Cells, L"^-1)), fill = "") +
  guides(color = F) +
  scale_color_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) +
  theme_bw()
```

# exponential phase of growth 
```{r}
ln_cells <- cells %>%
  group_by(Treatment, Bottle) %>% 
  mutate(ln_cells = log(cells),
         diff_ln_cells = ln_cells - lag(ln_cells, default = first(ln_cells))) %>% 
  ungroup()
```
```{r fig.height=4, fig.width=10}
ln_cells %>% 
  mutate(dna = ifelse(DNA_Sample == T, "*", NA)) %>% 
  ggplot(aes(x = days, y = diff_ln_cells, group = interaction(Treatment, Bottle))) +
  geom_line(aes(color = factor(Treatment, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(Treatment, levels = levels)), size = 3, color = "black", shape = 21) +
  geom_text(aes(label = dna), size = 12,  color = "#E41A1C") +
  labs(x = "Days", y = expression(paste("∆ln cells, L"^-1)), fill = "") +
  guides(color = F) +
  scale_color_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) +
  facet_grid(~Bottle, scales = "free") +
  theme_bw() 
```

```{r}
growth <- ln_cells %>% 
  mutate(exp_start = 0,
         exp_end = ifelse(!Bottle %in% c("G", "H"), 1, 2)) %>% 
  group_by(Treatment, Bottle) %>% 
  mutate(ln_cells_exp_start = ifelse(Timepoint == exp_start, ln_cells, NA), 
         ln_cells_exp_end = ifelse(Timepoint == exp_end, ln_cells, NA), 
         cells_exp_start = ifelse(Timepoint == exp_start, cells, NA), 
         cells_exp_end = ifelse(Timepoint == exp_end, cells, NA), 
         days_exp_start = ifelse(Timepoint == exp_start, days, NA), 
         days_exp_end = ifelse(Timepoint == exp_end, days, NA), ) %>% 
  fill(ln_cells_exp_start:days_exp_end, .direction = "updown") %>% 
  mutate(mew = (ln_cells_exp_end - ln_cells_exp_start)/(days_exp_end - days_exp_start), 
         doubling = log(2)/mew,
         delta_cells = cells_exp_end - first(cells)) %>% 
  ungroup()

glimpse(growth)
```

# Convert bacterial abundance & change in bacterial abundance to carbon units
```{r}
bactcarbon <- growth %>% 
  mutate(bc = cells * (2.5 * 10^-9), 
         delta_bc = delta_cells * (2.5 * 10^-9))

glimpse(bactcarbon)
```

# Calculate treatment averages
```{r}
averages <- bactcarbon %>%
  group_by(Treatment, Timepoint) %>% 
  mutate(ave_bc = mean(bc),
         sd_bc = sd(bc)) %>% 
  ungroup() %>% 
  group_by(Treatment) %>% 
  mutate(ave_mew = mean(mew),
         sd_mew = sd(mew),
         ave_doubling = mean(doubling),
         sd_doubling = sd(doubling),
         ave_delta_cells = mean(delta_cells),
         sd_delta_cells = sd(delta_cells),
         ave_delta_bc = mean(delta_bc),
         sd_delta_bc = sd(delta_bc),
         ave_lag = mean(days_exp_start),
         sd_lag = sd(days_exp_start)
  ) %>% 
  ungroup()
  
glimpse(averages)  
```

# Plot treatment averages
```{r fig.height=4, fig.width=6}
trt_ba <- averages %>% 
  ggplot(aes(x = days, y = ave_bc), group = interaction(Experiment, Treatment)) +
  geom_errorbar(aes(ymin = ave_bc - sd_bc, ymax = ave_bc + sd_bc, color = factor(Treatment, levels = levels)), width = 0.1) +
  geom_line(aes(color = factor(Treatment, levels = levels)), size = 1) +
  geom_point(aes(fill = factor(Treatment, levels = levels)), color = "black", shape = 21, size = 3) +
  scale_color_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) +
  labs(x = "Days", y = expression("Bacterial Carbon, µmol C L"^-1), fill = "", color = "") +
  guides(color = F) +
  theme_bw()

trt_ba

saveRDS(trt_ba, "Output_Data/week 3/144L_trt_ba_plot.rds")
```

## Barplots
```{r}
bar.data <- averages %>% 
  select(Treatment, ave_mew:sd_lag) %>% 
  distinct()
```

```{r}
mew <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_mew), group = interaction(Location, Treatment)) +
  geom_col(color = "black", fill = "white") +
  geom_errorbar(aes(ymin = ave_mew - sd_mew, ymax = ave_mew + sd_mew), width = 0.1) +
  labs(x = "", y = expression("µ, d"^-1)) +
  theme_bw()
```

```{r}
doubling <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_doubling), group = interaction(Location, Treatment)) +
  geom_col(color = "black", fill = "white") +
  geom_errorbar(aes(ymin = ave_doubling - sd_doubling, ymax = ave_doubling + sd_doubling), width = 0.1) +
  labs(x = "", y = expression("Doubling Time, d")) +
  theme_bw()
```

```{r}
delta_bc <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_delta_bc), group = interaction(Location, Treatment)) +
  geom_col(color = "black", fill = "white") +
  geom_errorbar(aes(ymin = ave_delta_bc - sd_delta_bc, ymax = ave_delta_bc + sd_delta_bc), width = 0.1) +
  labs(x = "", y = expression("∆ Bacterial Carbon, µmol C L"^-1)) +
  theme_bw()
```

```{r}
lag <- bar.data %>% 
  ggplot(aes(x = factor(Treatment, levels = levels), y = ave_lag), group = interaction(Location, Treatment)) +
  geom_col(color = "black", fill = "white") +
  geom_errorbar(aes(ymin = ave_lag - sd_lag, ymax = ave_lag + sd_lag), width = 0.1) +
  labs(x = "", y = "Lag Phase, days") +
  theme_bw()
```

```{r}
# install.packages("patchwork")
library(patchwork)
```

```{r fig.height=4, fig.width=8}
delta_bc + mew + doubling + plot_annotation(tag_levels = "a")
```

# save data
```{r}
saveRDS(averages, "Output_Data/week 3/144L_Exp_Processed_BactAbund.rds")
```









